name: security_bear_dart
description: Easy and secure way to connect to your device for maintenance.
version: 1.1.1
homepage: https://github.com/CyBear-Jinni/Security-Bear

environment:
  sdk: ^2.14.3

dependencies:
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.0
  # Convert enum to string
  enum_to_string: ^2.0.1
  # Allow returning more than one type of object
  equatable: ^2.0.3
  # Firebase Auth and Firestore SDKs.
  firedart: ^0.9.0+1
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.2.0
  # Key-value database
  hive: ^2.0.4
  # Checks for an internet connection by opening a socket
  internet_connection_checker: ^0.0.1+3
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.12.2+2
  # Provides parse, inspect, and manipulate stack traces
  stack_trace: ^1.10.0


dev_dependencies:
  build_runner:
  hive_generator: ^1.1.1
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.7.2
  # Library for mocks
  mockito: ^5.0.16
  test: ^1.19.3



