name: security_bear
description: Easy and secure way to connect to your device for maintenance.
version: 2.1.2+1
homepage: https://github.com/CyBear-Jinni/security_bear

environment:
  sdk: ^2.15.1

dependencies:
  # Contains utility classes in the style of dart:async to work with asynchronous computations.
  async: ^2.9.0
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.1
  # Allow returning more than one type of object
  equatable: ^2.0.3
  firedart: ^0.9.0+1
  # Annotations for freezed
  freezed_annotation: ^2.0.3
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.2.0
  # High performance, open-source universal RPC framework
  grpc: ^3.0.2
  # Lightweight and blazing fast key-value database
  hive: ^2.1.0
  # Convenient code generator for get_it
  injectable: ^1.5.3
  # Checks for an internet connection by opening a socket
  internet_connection_checker: ^0.0.1+3
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.5.0
  # Dart Build System builders for handling JSON.
  json_serializable: ^6.2.0
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^0.10.0
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.12.3+2
  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^2.0.1
  # Extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.3
  # Provides parse, inspect, and manipulate stack traces
  stack_trace: ^1.10.0
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.6


dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:

  # A generator for injectable library
  # Code generator for unions/pattern-matching/copy.
  freezed: ^2.0.3
  # Automatically generates Hive TypeAdapters to store any class
  hive_generator: ^1.1.2
  # Injectable is a convenient code generator for get_it.
  injectable_generator: ^1.5.3
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.8.2
  # Library for mocks
  mockito: ^5.1.0
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.21.1



