name: security_bear
description: Easy and secure way to connect to your device for maintenance.
version: 2.1.3
homepage: https://github.com/CyBear-Jinni/security_bear

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Contains utility classes in the style of dart:async to work with asynchronous computations.
  async: ^2.11.0
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.1
  # Allow returning more than one type of object
  equatable: ^2.0.5
  firedart: ^0.9.7
  # Annotations for freezed
  freezed_annotation: ^2.4.1
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.6.4
  # High performance, open-source universal RPC framework
  grpc: ^3.2.4
  # Lightweight and blazing fast key-value database
  hive: ^2.2.3
  # Convenient code generator for get_it
  injectable: ^2.3.2
  # Checks for an internet connection by opening a socket
  internet_connection_checker: ^1.0.0+1
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.1
  # Dart Build System builders for handling JSON.
  json_serializable: ^6.7.1
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^1.1.0
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.0.2+1
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.13.3
  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^3.1.0
  # Extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.7
  # Provides parse, inspect, and manipulate stack traces
  stack_trace: ^1.11.1
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^4.2.1


dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner:

  # A generator for injectable library
  # Code generator for unions/pattern-matching/copy.
  freezed: ^2.4.5
  # Automatically generates Hive TypeAdapters to store any class
  hive_generator: ^2.0.1
  # Injectable is a convenient code generator for get_it.
  injectable_generator: ^2.4.1
  # Collection of lint rules for Dart and Flutter projects
  lint: ^2.2.0
  # Library for mocks
  mockito: ^5.4.3
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.24.9